# Generated by Django 3.0.8 on 2020-08-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='img_url',
            new_name='image',
        ),
    ]
