# Generated by Django 3.0.8 on 2020-08-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200819_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_watchlist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
